name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 instance
      id: ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0d1c1cf7b44e1381f --count 1 --instance-type g4dn.xlarge --query 'Instances[0].InstanceId' --output text)
        echo "::set-output name=instance_id::$INSTANCE_ID"

    - name: Wait for instance to be running
      run: |
        aws ec2 wait instance-running --instance-ids ${{ steps.ec2.outputs.instance_id }}

    - name: Execute remote commands on EC2 instance
      run: |
        PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ steps.ec2.outputs.instance_id }} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
        ssh -o StrictHostKeyChecking=no -i /home/moonchild/matrix_key_pair.pem ec2-user@$PUBLIC_IP 'your commands here'

    - name: Terminate EC2 instance
      run: |
        aws ec2 terminate-instances --instance-ids ${{ steps.ec2.outputs.instance_id }}
